import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('language') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'te' : 'en');
  };

  const t = (key) => {
    return translations[language]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

const translations = {
  en: {
    // Navigation
    'Dashboard': 'Dashboard',
    'Main Dashboard': 'Main Dashboard',
    'Overview': 'Overview',
    'Analytics': 'Analytics',
    'Grain Analytics': 'Grain Analytics',
    'Payments': 'Payments',
    'Merchants': 'Merchants',
    'Products': 'Products',
    'Addresses': 'Addresses',
    'Profile': 'Profile',
    'All Services': 'All Services',
    'Profile Settings': 'Profile Settings',
    'Brokerage': 'Brokerage',
    'Ledger': 'Ledger',
    'Entities': 'Entities',
    'About': 'About',
    'User Brokerage': 'User Brokerage',
    'Bulk Operations': 'Bulk Operations',
    'Daily Ledger': 'Daily Ledger',
    'Calendar View': 'Calendar View',
    'JSON Transaction Input': 'JSON Transaction Input',
    'Payment Management': 'Payment Management',
    'Financial Years': 'Financial Years',
    'Create Merchant': 'Create Merchant',
    'Phone Directory': 'Phone Directory',
    'About BrokerHub': 'About BrokerHub',
    'Logout': 'Logout',
    'NAVIGATION': 'NAVIGATION',
    
    // Common
    'Welcome back': 'Welcome back',
    'Loading...': 'Loading...',
    'Save': 'Save',
    'Cancel': 'Cancel',
    'Edit': 'Edit',
    'Delete': 'Delete',
    'Add': 'Add',
    'Search': 'Search',
    'Filter': 'Filter',
    'Export': 'Export',
    'Import': 'Import',
    'Refresh': 'Refresh',
    'Back': 'Back',
    'Next': 'Next',
    'Previous': 'Previous',
    'Submit': 'Submit',
    'Close': 'Close',
    'View': 'View',
    
    // Dashboard
    'BrokerHub Dashboard': 'BrokerHub Dashboard',
    'Total Sales': 'Total Sales',
    'Total Quantity': 'Total Quantity',
    'Total Transactions': 'Total Transactions',
    'Total Brokerage Earned': 'Total Brokerage Earned',
    'Total Transaction Value': 'Total Transaction Value',
    'Active Merchants': 'Active Merchants',
    'Open Ledger Detail': 'Open Ledger Detail',
    'Ledger Management': 'Ledger Management',
    'Brokerage Dashboard': 'Brokerage Dashboard',
    'Top Buyers': 'Top Buyers',
    'Top Sellers': 'Top Sellers',
    'Coming Soon': 'Coming Soon',
    'Audit Ledger Management': 'Audit Ledger Management',
    'Monthly Sales Performance': 'Monthly Sales Performance',
    'Product Distribution': 'Product Distribution',
    
    // Payments
    'Brokerage Payments': 'Brokerage Payments',
    'Pending Payments': 'Pending Payments',
    'Receivable Payments': 'Receivable Payments',
    'Payment Dashboard': 'Payment Dashboard',
    'Total Pending': 'Total Pending',
    'Firm Name': 'Firm Name',
    'Total Bags': 'Total Bags',
    'Rate': 'Rate',
    'Net Brokerage': 'Net Brokerage',
    'Paid Amount': 'Paid Amount',
    'Pending Amount': 'Pending Amount',
    'Status': 'Status',
    'Actions': 'Actions',
    'View Details': 'View Details',
    'Add Payment': 'Add Payment',
    
    // Merchants
    'Merchant Directory': 'Merchant Directory',
    'Add New Merchant': 'Add New Merchant',
    'Bulk Upload': 'Bulk Upload',
    'City': 'City',
    'Total Brokerage': 'Total Brokerage',
    'No Merchants Found': 'No Merchants Found',
    
    // Products
    'Product Catalog': 'Product Catalog',
    'Add New Product': 'Add New Product',
    'No Products Found': 'No Products Found',
    
    // Profile
    'Broker Information': 'Broker Information',
    'Broker ID': 'Broker ID',
    'Name': 'Name',
    'Username': 'Username',
    'Phone': 'Phone',
    'Email': 'Email',
    'Address & Banking': 'Address & Banking',
    'Settings & Actions': 'Settings & Actions',
    'Change Password': 'Change Password',
    'Update Profile': 'Update Profile',
    'Verify Account': 'Verify Account',
    'Current Financial Year': 'Current Financial Year',
    'Quick Actions': 'Quick Actions',
    'Refresh Profile': 'Refresh Profile',
    
    // Addresses
    'Address Management': 'Address Management',
    'Route Explorer': 'Route Explorer',
    'Add Address': 'Add Address',
    
    // Calendar
    'Analytics Overview': 'Analytics Overview',
    
    // Audit Ledger
    'Manage financial years, track transactions, and audit your business records with our comprehensive ledger system.': 'Manage financial years, track transactions, and audit your business records with our comprehensive ledger system.',
    'Financial Year Management': 'Financial Year Management',
    'Transaction Tracking': 'Transaction Tracking',
    'Audit Reports': 'Audit Reports',
    'Start managing your financial records': 'Start managing your financial records',
    
    // All Services
    'All services will be available here soon.': 'All services will be available here soon.',
    'Merchants by City': 'Merchants by City',
    'Merchants in City': 'Merchants in City',
    'Browse and search merchants organized by their city location': 'Browse and search merchants organized by their city location',
    'Available Cities': 'Available Cities',
    'Search cities...': 'Search cities...',
    'Merchants in': 'Merchants in',
    'Search merchants by name or phone...': 'Search merchants by name or phone...',
    'No cities found': 'No cities found',
    'No Merchants Found': 'No Merchants Found',
    'No merchants match your search.': 'No merchants match your search.',
    'No merchants available in': 'No merchants available in',
    'Loading cities...': 'Loading cities...',
    'Loading merchants...': 'Loading merchants...',
    'Total Bags Sold': 'Total Bags Sold',
    'Total Bags Bought': 'Total Bags Bought',
    'Payable Amount': 'Payable Amount',
    'Receivable Amount': 'Receivable Amount',
    'Total Brokerage': 'Total Brokerage',
    'Contact Numbers': 'Contact Numbers',
    
    // Financial Years
    'Financial Year Management': 'Financial Year Management',
    'Manage your financial years': 'Manage your financial years',
    'Add Financial Year': 'Add Financial Year',
    'Year Name': 'Year Name',
    'Start Date': 'Start Date',
    'End Date': 'End Date',
    'Set as Current': 'Set as Current',
    
    // Daily Ledger
    'Daily Ledger': 'Daily Ledger',
    'Transaction Details': 'Transaction Details',
    'Date': 'Date',
    'Seller': 'Seller',
    'Buyer': 'Buyer',
    'Product': 'Product',
    'Quantity': 'Quantity',
    'Price': 'Price',
    'Amount': 'Amount',
    
    // Brokerage
    'User Brokerage Details': 'User Brokerage Details',
    'Brokerage Summary': 'Brokerage Summary',
    'Total Earned': 'Total Earned',
    'Pending Collection': 'Pending Collection',
    'Collected': 'Collected',
    'Per Bag Rate': 'Per Bag Rate',
    'Total Bags': 'Total Bags',
    
    // Grain Analytics
    'Grain Analytics': 'Grain Analytics',
    'Market Trends': 'Market Trends',
    'Price Analysis': 'Price Analysis',
    'Supply & Demand': 'Supply & Demand',
    'Forecast': 'Forecast',
  },
  te: {
    // Navigation
    'Dashboard': 'డాష్బోర్డ్',
    'Main Dashboard': 'ప్రధాన డాష్బోర్డ్',
    'Overview': 'అవలోకనం',
    'Analytics': 'విశ్లేషణలు',
    'Grain Analytics': 'ధాన్యం విశ్లేషణలు',
    'Payments': 'చెల్లింపులు',
    'Merchants': 'వ్యాపారులు',
    'Products': 'ఉత్పత్తులు',
    'Addresses': 'చిరునామాలు',
    'Profile': 'ప్రొఫైల్',
    'All Services': 'అన్ని సేవలు',
    'Profile Settings': 'ప్రొఫైల్ సెట్టింగ్లు',
    'Brokerage': 'బ్రోకరేజ్',
    'Ledger': 'లెడ్జర్',
    'Entities': 'సంస్థలు',
    'About': 'గురించి',
    'User Brokerage': 'యూజర్ బ్రోకరేజ్',
    'Bulk Operations': 'బల్క్ కార్యకలాపాలు',
    'Daily Ledger': 'రోజువారీ లెడ్జర్',
    'Calendar View': 'క్యాలెండర్ వీక్షణ',
    'JSON Transaction Input': 'JSON లావాదేవీ ఇన్పుట్',
    'Payment Management': 'చెల్లింపు నిర్వహణ',
    'Financial Years': 'ఆర్థిక సంవత్సరాలు',
    'Create Merchant': 'వ్యాపారి సృష్టించండి',
    'Phone Directory': 'ఫోన్ డైరెక్టరీ',
    'About BrokerHub': 'బ్రోకర్హబ్ గురించి',
    'Logout': 'లాగ్అవుట్',
    'NAVIGATION': 'నావిగేషన్',
    
    // Common
    'Welcome back': 'తిరిగి స్వాగతం',
    'Loading...': 'లోడ్ అవుతోంది...',
    'Save': 'సేవ్ చేయండి',
    'Cancel': 'రద్దు చేయండి',
    'Edit': 'సవరించండి',
    'Delete': 'తొలగించండి',
    'Add': 'జోడించండి',
    'Search': 'వెతకండి',
    'Filter': 'ఫిల్టర్',
    'Export': 'ఎగుమతి',
    'Import': 'దిగుమతి',
    'Refresh': 'రిఫ్రెష్',
    'Back': 'వెనుకకు',
    'Next': 'తదుపరి',
    'Previous': 'మునుపటి',
    'Submit': 'సమర్పించండి',
    'Close': 'మూసివేయండి',
    'View': 'చూడండి',
    
    // Dashboard
    'BrokerHub Dashboard': 'బ్రోకర్హబ్ డాష్బోర్డ్',
    'Total Sales': 'మొత్తం అమ్మకాలు',
    'Total Quantity': 'మొత్తం పరిమాణం',
    'Total Transactions': 'మొత్తం లావాదేవీలు',
    'Total Brokerage Earned': 'మొత్తం బ్రోకరేజ్ సంపాదన',
    'Total Transaction Value': 'మొత్తం లావాదేవీ విలువ',
    'Active Merchants': 'క్రియాశీల వ్యాపారులు',
    'Open Ledger Detail': 'లెడ్జర్ వివరాలు తెరవండి',
    'Ledger Management': 'లెడ్జర్ నిర్వహణ',
    'Brokerage Dashboard': 'బ్రోకరేజ్ డాష్బోర్డ్',
    'Top Buyers': 'టాప్ కొనుగోలుదారులు',
    'Top Sellers': 'టాప్ అమ్మకందారులు',
    'Coming Soon': 'త్వరలో వస్తోంది',
    'Audit Ledger Management': 'ఆడిట్ లెడ్జర్ నిర్వహణ',
    'Monthly Sales Performance': 'నెలవారీ అమ్మకాల పనితీరు',
    'Product Distribution': 'ఉత్పత్తి పంపిణీ',
    
    // All Services
    'Merchants by City': 'నగరం వారీగా వ్యాపారులు',
    'Merchants in City': 'నగరంలో వ్యాపారులు',
    'Browse and search merchants organized by their city location': 'వారి నగర స్థానం ద్వారా వ్యాపారులను బ్రౌజ్ చేయండి మరియు శోధించండి',
    'Available Cities': 'అందుబాటులో ఉన్న నగరాలు',
    'Search cities...': 'నగరాలను వెతకండి...',
    'Merchants in': 'వ్యాపారులు',
    'Search merchants by name or phone...': 'పేరు లేదా ఫోన్ ద్వారా వ్యాపారులను వెతకండి...',
    'No cities found': 'నగరాలు కనుగొనబడలేదు',
    'No Merchants Found': 'వ్యాపారులు కనుగొనబడలేదు',
    'No merchants match your search.': 'మీ శోధనకు సరిపోయే వ్యాపారులు లేరు.',
    'No merchants available in': 'లో వ్యాపారులు అందుబాటులో లేరు',
    'Loading cities...': 'నగరాలు లోడ్ అవుతున్నాయి...',
    'Loading merchants...': 'వ్యాపారులు లోడ్ అవుతున్నారు...',
    'Total Bags Sold': 'మొత్తం సంచులు అమ్మకాలు',
    'Total Bags Bought': 'మొత్తం సంచులు కొనుగోళ్లు',
    'Payable Amount': 'చెల్లించవలసిన మొత్తం',
    'Receivable Amount': 'స్వీకరించవలసిన మొత్తం',
    'Total Brokerage': 'మొత్తం బ్రోకరేజ్',
    'Contact Numbers': 'సంప్రదింపు నంబర్లు',

    // Payments
    'Brokerage Payments': 'బ్రోకరేజ్ చెల్లింపులు',
    'Pending Payments': 'పెండింగ్ చెల్లింపులు',
    'Receivable Payments': 'స్వీకరించదగిన చెల్లింపులు',
    'Payment Dashboard': 'చెల్లింపు డాష్బోర్డ్',
    'Total Pending': 'మొత్తం పెండింగ్',
    'Firm Name': 'సంస్థ పేరు',
    'Total Bags': 'మొత్తం సంచులు',
    'Rate': 'రేటు',
    'Net Brokerage': 'నికర బ్రోకరేజ్',
    'Paid Amount': 'చెల్లించిన మొత్తం',
    'Pending Amount': 'పెండింగ్ మొత్తం',
    'Status': 'స్థితి',
    'Actions': 'చర్యలు',
    'View Details': 'వివరాలు చూడండి',
    'Add Payment': 'చెల్లింపు జోడించండి',
    
    // Merchants
    'Merchant Directory': 'వ్యాపారుల డైరెక్టరీ',
    'Add New Merchant': 'కొత్త వ్యాపారి జోడించండి',
    'Bulk Upload': 'బల్క్ అప్లోడ్',
    'City': 'నగరం',
    'Total Brokerage': 'మొత్తం బ్రోకరేజ్',
    'No Merchants Found': 'వ్యాపారులు కనుగొనబడలేదు',
    
    // Products
    'Product Catalog': 'ఉత్పత్తి జాబితా',
    'Add New Product': 'కొత్త ఉత్పత్తి జోడించండి',
    'No Products Found': 'ఉత్పత్తులు కనుగొనబడలేదు',
    
    // Profile
    'Broker Information': 'బ్రోకర్ సమాచారం',
    'Broker ID': 'బ్రోకర్ ID',
    'Name': 'పేరు',
    'Username': 'యూజర్నేమ్',
    'Phone': 'ఫోన్',
    'Email': 'ఇమెయిల్',
    'Address & Banking': 'చిరునామా & బ్యాంకింగ్',
    'Settings & Actions': 'సెట్టింగ్లు & చర్యలు',
    'Change Password': 'పాస్వర్డ్ మార్చండి',
    'Update Profile': 'ప్రొఫైల్ అప్డేట్ చేయండి',
    'Verify Account': 'ఖాతా ధృవీకరించండి',
    'Current Financial Year': 'ప్రస్తుత ఆర్థిక సంవత్సరం',
    'Quick Actions': 'త్వరిత చర్యలు',
    'Refresh Profile': 'ప్రొఫైల్ రిఫ్రెష్ చేయండి',
    
    // Addresses
    'Address Management': 'చిరునామా నిర్వహణ',
    'Route Explorer': 'రూట్ ఎక్స్ప్లోరర్',
    'Add Address': 'చిరునామా జోడించండి',
    
    // Calendar
    'Analytics Overview': 'విశ్లేషణల అవలోకనం',
    
    // Audit Ledger
    'Manage financial years, track transactions, and audit your business records with our comprehensive ledger system.': 'మా సమగ్ర లెడ్జర్ వ్యవస్థతో ఆర్థిక సంవత్సరాలను నిర్వహించండి, లావాదేవీలను ట్రాక్ చేయండి మరియు మీ వ్యాపార రికార్డులను ఆడిట్ చేయండి.',
    'Financial Year Management': 'ఆర్థిక సంవత్సర నిర్వహణ',
    'Transaction Tracking': 'లావాదేవీ ట్రాకింగ్',
    'Audit Reports': 'ఆడిట్ నివేదికలు',
    'Start managing your financial records': 'మీ ఆర్థిక రికార్డులను నిర్వహించడం ప్రారంభించండి',
    
    // All Services
    'All services will be available here soon.': 'అన్ని సేవలు త్వరలో ఇక్కడ అందుబాటులో ఉంటాయి.',
    
    // Financial Years
    'Manage your financial years': 'మీ ఆర్థిక సంవత్సరాలను నిర్వహించండి',
    'Add Financial Year': 'ఆర్థిక సంవత్సరం జోడించండి',
    'Year Name': 'సంవత్సర పేరు',
    'Start Date': 'ప్రారంభ తేదీ',
    'End Date': 'ముగింపు తేదీ',
    'Set as Current': 'ప్రస్తుతంగా సెట్ చేయండి',
    
    // Daily Ledger
    'Transaction Details': 'లావాదేవీ వివరాలు',
    'Date': 'తేదీ',
    'Seller': 'అమ్మకందారుడు',
    'Buyer': 'కొనుగోలుదారుడు',
    'Product': 'ఉత్పత్తి',
    'Quantity': 'పరిమాణం',
    'Price': 'ధర',
    'Amount': 'మొత్తం',
    
    // Brokerage
    'User Brokerage Details': 'యూజర్ బ్రోకరేజ్ వివరాలు',
    'Brokerage Summary': 'బ్రోకరేజ్ సారాంశం',
    'Total Earned': 'మొత్తం సంపాదన',
    'Pending Collection': 'పెండింగ్ సేకరణ',
    'Collected': 'సేకరించబడింది',
    'Per Bag Rate': 'ప్రతి సంచి రేటు',
    
    // Grain Analytics
    'Market Trends': 'మార్కెట్ ట్రెండ్స్',
    'Price Analysis': 'ధర విశ్లేషణ',
    'Supply & Demand': 'సరఫరా & డిమాండ్',
    'Forecast': 'అంచనా',
    
    // Payment Details
    'Loading brokerage payments...': 'బ్రోకరేజ్ చెల్లింపులు లోడ్ అవుతున్నాయి...',
    'Search by firm name...': 'సంస్థ పేరుతో వెతకండి...',
    'Clear': 'క్లియర్',
    'Owner:': 'యజమాని:',
    'Gross Brokerage:': 'మొత్తం బ్రోకరేజ్:',
    'Net Brokerage:': 'నికర బ్రోకరేజ్:',
    'Paid Amount:': 'చెల్లించిన మొత్తం:',
    'Pending Amount:': 'పెండింగ్ మొత్తం:',
    'Last Payment:': 'చివరి చెల్లింపు:',
    'Due Date:': 'గడువు తేదీ:',
    'Complete': 'పూర్తి',
    'Payment History': 'చెల్లింపు చరిత్ర',
    'No brokerage payments found': 'బ్రోకరేజ్ చెల్లింపులు కనుగొనబడలేదు',
    'Add Part Payment': 'పార్ట్ చెల్లింపు జోడించండి',
    'Amount *': 'మొత్తం *',
    'Payment Method *': 'చెల్లింపు పద్ధతి *',
    'Payment Date *': 'చెల్లింపు తేదీ *',
    'Transaction Reference *': 'లావాదేవీ సూచన *',
    'Bank Details': 'బ్యాంక్ వివరాలు',
    'Notes': 'గమనికలు',
    'Maximum:': 'గరిష్టం:',
    'Enter payment amount': 'చెల్లింపు మొత్తం నమోదు చేయండి',
    'Enter transaction reference': 'లావాదేవీ సూచన నమోదు చేయండి',
    'Enter bank details': 'బ్యాంక్ వివరాలు నమోదు చేయండి',
    'Add any notes about this payment': 'ఈ చెల్లింపు గురించి ఏవైనా గమనికలు జోడించండి',
    'Adding Payment...': 'చెల్లింపు జోడిస్తోంది...',
    'Loading pending payments...': 'పెండింగ్ చెల్లింపులు లోడ్ అవుతున్నాయి...',
    'Search by buyer firm...': 'కొనుగోలుదారు సంస్థతో వెతకండి...',
    'Buyer Owner:': 'కొనుగోలుదారు యజమాని:',
    'User Type:': 'యూజర్ రకం:',
    'Total Pending:': 'మొత్తం పెండింగ్:',
    'Transactions:': 'లావాదేవీలు:',
    'Oldest Transaction:': 'పాత లావాదేవీ:',
    'Days Overdue:': 'ఆలస్యమైన రోజులు:',
    'Days Until Due:': 'గడువు వరకు రోజులు:',
    'days': 'రోజులు',
    'Recent Transactions': 'ఇటీవలి లావాదేవీలు',
    'more transactions': 'మరిన్ని లావాదేవీలు',
    'No pending payments found': 'పెండింగ్ చెల్లింపులు కనుగొనబడలేదు',
    'Loading receivable payments...': 'స్వీకరించదగిన చెల్లింపులు లోడ్ అవుతున్నాయి...',
    'Search by seller firm...': 'అమ్మకందారు సంస్థతో వెతకండి...',
    'Seller Owner:': 'అమ్మకందారు యజమాని:',
    'Total Receivable:': 'మొత్తం స్వీకరించదగినది:',
    'Unique Buyers:': 'ప్రత్యేక కొనుగోలుదారులు:',
    'Largest Debt:': 'అతిపెద్ద అప్పు:',
    'Owed By': 'రుణపడినవారు',
    'buyers': 'కొనుగోలుదారులు',
    'more buyers': 'మరిన్ని కొనుగోలుదారులు',
    'No receivable payments found': 'స్వీకరించదగిన చెల్లింపులు కనుగొనబడలేదు',
    'Loading dashboard statistics...': 'డాష్బోర్డ్ గణాంకాలు లోడ్ అవుతున్నాయి...',
    'Completion Rate': 'పూర్తి రేటు',
    'Merchants with Pending:': 'పెండింగ్ ఉన్న వ్యాపారులు:',
    'Overdue:': 'ఆలస్యం:',
    'Buyers with Pending': 'పెండింగ్ ఉన్న కొనుగోలుదారులు',
    'Overdue Payments': 'ఆలస్యమైన చెల్లింపులు',
    'Average Amount': 'సగటు మొత్తం',
    'Total Receivable': 'మొత్తం స్వీకరించదగినది',
    'Sellers with Receivable': 'స్వీకరించదగిన అమ్మకందారులు',
    'Overdue Receivables': 'ఆలస్యమైన స్వీకరణలు',
    'Overall Summary': 'మొత్తం సారాంశం',
    'Total Amount in Circulation': 'చలామణిలో ఉన్న మొత్తం మొత్తం',
    'Active Payments': 'క్రియాశీల చెల్లింపులు',
    'Critical Payments': 'క్లిష్టమైన చెల్లింపులు',
    'Due Soon': 'త్వరలో గడువు',
    'Recent Payments': 'ఇటీవలి చెల్లింపులు',
    
    // Merchant Details
    'Merchant Details': 'వ్యాపారి వివరాలు',
    'Basic Information': 'ప్రాథమిక సమాచారం',
    'Owner Name': 'యజమాని పేరు',
    'GST Number': 'GST నంబర్',
    'Contact Information': 'సంప్రదింపు సమాచారం',
    'Address': 'చిరునామా',
    'Trading Summary': 'వ్యాపార సారాంశం',
    'Bags Sold': 'అమ్మిన సంచులు',
    'Bags Bought': 'కొనుగోలు చేసిన సంచులు',
    'Brokerage Rate': 'బ్రోకరేజ్ రేటు',
    'Financial Summary': 'ఆర్థిక సారాంశం',
    'Payable Amount': 'చెల్లించవలసిన మొత్తం',
    'Receivable Amount': 'స్వీకరించదగిన మొత్తం',
    'Print City Bill': 'సిటీ బిల్లు ప్రింట్ చేయండి',
    'Generating...': 'రూపొందిస్తోంది...',
    
    // Product Modal
    'Create a new product entry': 'కొత్త ఉత్పత్తి ఎంట్రీ సృష్టించండి',
    'Product Name': 'ఉత్పత్తి పేరు',
    'Quality': 'నాణ్యత',
    'Quantity (kg)': 'పరిమాణం (కిలోలు)',
    'Price (₹)': 'ధర (₹)',
    'Product Brokerage (₹)': 'ఉత్పత్తి బ్రోకరేజ్ (₹)',
    'Create Product': 'ఉత్పత్తి సృష్టించండి',
    'e.g., Rice': 'ఉదా., బియ్యం',
    'e.g., Premium': 'ఉదా., ప్రీమియం',
    
    // Auth Pages
    'Welcome to BrokerHub': 'బ్రోకర్హబ్కు స్వాగతం',
    'Sign in to your account to continue': 'కొనసాగించడానికి మీ ఖాతాలోకి సైన్ ఇన్ చేయండి',
    'Password': 'పాస్వర్డ్',
    'Enter your username': 'మీ యూజర్నేమ్ నమోదు చేయండి',
    'Enter your password': 'మీ పాస్వర్డ్ నమోదు చేయండి',
    'Sign In': 'సైన్ ఇన్',
    'Forgot your password?': 'మీ పాస్వర్డ్ మర్చిపోయారా?',
    'Create Password': 'పాస్వర్డ్ సృష్టించండి',
    "Don't have an account?": 'ఖాతా లేదా?',
    'Create Account': 'ఖాతా సృష్టించండి',
    'Create Your BrokerHub Account': 'మీ బ్రోకర్హబ్ ఖాతా సృష్టించండి',
    'Join the platform for rice, dals, and grains trading': 'బియ్యం, పప్పులు మరియు ధాన్యాల వ్యాపారం కోసం ప్లాట్ఫార్మ్లో చేరండి',
    'Account': 'ఖాతా',
    'Contact': 'సంప్రదింపు',
    'Banking': 'బ్యాంకింగ్',
    'Brokerage Firm Name *': 'బ్రోకరేజ్ సంస్థ పేరు *',
    'Enter your unique firm/company name': 'మీ ప్రత్యేక సంస్థ/కంపెనీ పేరు నమోదు చేయండి',
    'This name will be used for all business transactions and documents': 'ఈ పేరు అన్ని వ్యాపార లావాదేవీలు మరియు పత్రాలకు ఉపయోగించబడుతుంది',
    'Choose a unique username': 'ప్రత్యేక యూజర్నేమ్ ఎంచుకోండి',
    'Username will be used for login and must be unique across the platform': 'యూజర్నేమ్ లాగిన్ కోసం ఉపయోగించబడుతుంది మరియు ప్లాట్ఫార్మ్లో ప్రత్యేకంగా ఉండాలి',
    'Create a strong password': 'బలమైన పాస్వర్డ్ సృష్టించండి',
    'Confirm Password': 'పాస్వర్డ్ నిర్ధారించండి',
    'Confirm your password': 'మీ పాస్వర్డ్ నిర్ధారించండి',
    'Broker Name': 'బ్రోకర్ పేరు',
    'Your full name': 'మీ పూర్తి పేరు',
    'Email Address': 'ఇమెయిల్ చిరునామా',
    'your.email@example.com': 'మీ.ఇమెయిల్@ఉదాహరణ.com',
    'Phone Number': 'ఫోన్ నంబర్',
    '10-digit mobile number': '10-అంకెల మొబైల్ నంబర్',
    'Pincode': 'పిన్కోడ్',
    '6-digit area pincode': '6-అంకెల ప్రాంత పిన్కోడ్',
    'Bank Name': 'బ్యాంక్ పేరు',
    'Your bank name': 'మీ బ్యాంక్ పేరు',
    'Account Number': 'ఖాతా నంబర్',
    'Bank account number': 'బ్యాంక్ ఖాతా నంబర్',
    'IFSC Code': 'IFSC కోడ్',
    'Bank IFSC code': 'బ్యాంక్ IFSC కోడ్',
    'Branch': 'శాఖ',
    'Bank branch name': 'బ్యాంక్ శాఖ పేరు',
    'Already have an account?': 'ఇప్పటికే ఖాతా ఉందా?',
    'Forgot Password?': 'పాస్వర్డ్ మర్చిపోయారా?',
    "Enter your username and we'll send an OTP to your email": 'మీ యూజర్నేమ్ నమోదు చేయండి మరియు మేము మీ ఇమెయిల్కు OTP పంపుతాము',
    'Send OTP': 'OTP పంపండి',
    'Remember your password? Sign in': 'మీ పాస్వర్డ్ గుర్తుందా? సైన్ ఇన్ చేయండి',
    'Update your account password': 'మీ ఖాతా పాస్వర్డ్ నవీకరించండి',
    'Current Password': 'ప్రస్తుత పాస్వర్డ్',
    'Enter your current password': 'మీ ప్రస్తుత పాస్వర్డ్ నమోదు చేయండి',
    'New Password': 'కొత్త పాస్వర్డ్',
    'Enter your new password': 'మీ కొత్త పాస్వర్డ్ నమోదు చేయండి',
    'Confirm New Password': 'కొత్త పాస్వర్డ్ నిర్ధారించండి',
    'Confirm your new password': 'మీ కొత్త పాస్వర్డ్ నిర్ధారించండి',
    'Your email address': 'మీ ఇమెయిల్ చిరునామా',
    
    // Common Messages
    'Failed to load': 'లోడ్ చేయడంలో విఫలమైంది',
    'Search failed': 'వెతకడం విఫలమైంది',
    'Please enter a valid amount': 'దయచేసి చెల్లుబాటు అయ్యే మొత్తం నమోదు చేయండి',
    'Amount cannot exceed pending amount': 'మొత్తం పెండింగ్ మొత్తం కంటే ఎక్కువ ఉండకూడదు',
    'Transaction reference is required for this payment method': 'ఈ చెల్లింపు పద్ధతికి లావాదేవీ సూచన అవసరం',
    'Failed to add payment': 'చెల్లింపు జోడించడంలో విఫలమైంది',
    'units': 'యూనిట్లు',
    'Since:': 'నుండి:',
    'PAID': 'చెల్లించబడింది',
    'PARTIALLY_PAID': 'పాక్షికంగా చెల్లించబడింది',
    'OVERDUE': 'ఆలస్యం',
    'PENDING': 'పెండింగ్',
    'HIGH': 'అధిక',
    'MEDIUM': 'మధ్యస్థ',
    'LOW': 'తక్కువ',
    'CRITICAL': 'క్లిష్టమైన',
    'CASH': 'నగదు',
    'CHEQUE': 'చెక్',
    'UPI': 'UPI',
    'BANK_TRANSFER': 'బ్యాంక్ బదిలీ',
    'NEFT': 'NEFT',
    'RTGS': 'RTGS',
    'CARD': 'కార్డ్',
  }
};

export default translations;
